localStorage.latestVersionNameSavings = "Savings 6.0";
localStorage.latestVersionCodeSavings = 60;
localStorage.downloadLinkSavings = "https://drive.google.com/file/d/1xOIC_tuCCqRuwtlSRdv03aNLLbLW7gFq/view?usp=drivesdk";
localStorage.downloadSizeSavings = "Copy Link (4.9Mb)";
localStorage.heighLightsSavings = "<p id='hlcnt' >Added password to view this link rel stylesheet to buy one response or lage to buy one get to know svg filter var--main-text-color white</p><p id='hlcnt' >Added password to view this link rel stylesheet to buy one response or lage to buy one get to know svg filter var--main-text-color white</p><p id='hlcnt' >Added password to view this link rel stylesheet to buy one response or lage to buy one get to know svg filter var--main-text-color white</p><p id='hlcnt' >Added password to view this link rel stylesheet to buy one response or lage to buy one get to know svg filter var--main-text-color white</p><p id='hlcnt' >Added password to view this link rel stylesheet to buy one response or lage to buy one get to know svg filter var--main-text-color white</p><p id='hlcnt' >Added password to view this link rel stylesheet to buy one response or lage to buy one get to know svg filter var--main-text-color white</p><p id='hlcnt' >Added password to view this link rel stylesheet to buy one response or lage to buy one get to know svg filter var--main-text-color white</p><p id='hlcnt' >Added password to view this link rel stylesheet to buy one response or lage to buy one get to know svg filter var--main-text-color white</p><p id='hlcnt' >Added password to view this link rel stylesheet to buy one response or lage to buy one get to know svg filter var--main-text-color white</p><p id='hlcnt' >Added password to view this link rel stylesheet to buy one response or lage to buy one get to know svg filter var--main-text-color white</p><p id='hlcnt' >Added password to view this link rel stylesheet to buy one response or lage to buy one get to know svg filter var--main-text-color white</p><p id='hlcnt' >Added password to view this link rel stylesheet to buy one response or lage to buy one get to know svg filter var--main-text-color white</p>";
if(Number(localStorage.latestVersionCodeSavings) > Number(localStorage.currentVersionCodeSavings)){
   localStorage.isUpdateAvailable = "yes";
}else{
   localStorage.isUpdateAvailable = "";
}